version: '3.7'
services:
  postgres:
    image: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - postgres
    deploy:
      mode: global
      resources:
        limits:
          memory: '2G'
        reservations:
          memory: '2G'
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.usage==storage
          - node.labels.type==large
          - node.labels.database==postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=nimda

  adminer:
    image: adminer
    ports:
      - 8010:8080
    networks:
      - postgres
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=nette

volumes:
  postgres:

networks:
  postgres:
    driver: overlay