version: '3.7'
services:
  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - "registry:/var/lib/registry"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1G'
        reservations:
          memory: '1G'
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.usage==storage
    environment:
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
  registry-ui:
    image: konradkleine/docker-registry-frontend:v2
    ports:
      - "10080:80"
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '128M'
        reservations:
          memory: '128M'
      restart_policy:
        condition: on-failure
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry
      - ENV_DOCKER_REGISTRY_PORT=5000

volumes:
  registry: