version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "11080:8080"
      - "50000:50000"
    volumes:
      - "jenkins:/var/jenkins_home"
    networks:
      - internet
    deploy:
      replicas: 1
      resources:
        limits:
          memory: '1G'
        reservations:
          memory: '1G'
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.usage==ci

volumes:
  jenkins:
networks:
  internet:
    driver: overlay